### ISSUE TITLE
error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by wzjscut** [AIR-DISCOVER/ICRA2024-Sim2Real-AXS#6]
When I run the baseline AXS_baseline.py in docker, it shows this log continuously.
What's the problems?

nvidia-smi shows below
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0  On |                  N/A |
| 66%   62C    P2             325W / 350W |  14375MiB / 24576MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

**Comment by wzjscut** [comment]
solved by updating torch

**Comment by DedSecer** [comment]
@wzjscut I encountered the same problem with you, could you please tell me which version you update and how you update the torch?

**Comment by GedRelay** [comment]
> @wzjscut I encountered the same problem with you, could you please tell me which version you update and how you update the torch?

I have the same error. Are you solved now?

**Comment by Yjjjjjjw** [comment]
> > @wzjscut I encountered the same problem with you, could you please tell me which version you update and how you update the torch?
> 
> I have the same error. Are you solved now?

I have the same error. Are you solved now?
